CREATE DATABASE GPS_LOCATION_SYSTEM;
USE GPS_LOCATION_SYSTEM;

CREATE TABLE USERS(
USERNAME VARCHAR(45) NOT NULL,
PASS VARCHAR(45) NOT NULL,
ENABLED TINYINT NOT NULL DEFAULT 1,
MAIL VARCHAR(45) NOT NULL,
PRIMARY KEY(USERNAME)
);

CREATE TABLE USER_ROLES(
USERNAME VARCHAR(45) NOT NULL,
ROLE VARCHAR(45) NOT NULL,
FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE TRACKS(
ID_TRACK INT NOT NULL AUTO_INCREMENT,
ID_SESSION INT,
SESSION_DATE DATE,
USERNAME VARCHAR(20),
PRIMARY KEY (ID_TRACK),
FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE COORDINATES(
LNG DOUBLE,
LAT DOUBLE,
ID_TRACK INT,
FOREIGN KEY(ID_TRACK) REFERENCES TRACKS(ID_TRACK)
)